// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRI.Project.Rosseel_Almanzo.Infrastructure.Data;

#nullable disable

namespace PRI.Project.Rosseel_Almanzo.Infrastructure.Migrations
{
    [DbContext(typeof(SniffHikesDbContext))]
    [Migration("20240426095341_seedUserClaims")]
    partial class seedUserClaims
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "10/05/1980 0:00:00",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "15/07/1985 0:00:00",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "admin@pri.be",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "user@pri.be",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "UserId",
                            ClaimValue = "1",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "UserId",
                            ClaimValue = "2",
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 2,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gent",
                            Country = "Belgie",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 15"
                        },
                        new
                        {
                            Id = 4,
                            City = "Brugge",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 28"
                        },
                        new
                        {
                            Id = 5,
                            City = "Veurne",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Ooststraat 10"
                        },
                        new
                        {
                            Id = 6,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 7,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 8,
                            City = "Antwerpen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Meir 12"
                        },
                        new
                        {
                            Id = 9,
                            City = "Leuven",
                            Country = "België",
                            State = "Vlaams-Brabant",
                            Street = "Grote Markt 1"
                        },
                        new
                        {
                            Id = 10,
                            City = "Mechelen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Groenplaats 21"
                        },
                        new
                        {
                            Id = 11,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Oude Burg 12"
                        },
                        new
                        {
                            Id = 12,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 13,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 14,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 15,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4857),
                            EventId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4860),
                            EventId = 2,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4861),
                            EventId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4863),
                            EventId = 3,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4865),
                            RouteId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4867),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4868),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4870),
                            RouteId = 3,
                            UserId = "4"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4799),
                            Gender = "Male",
                            Name = "Inca",
                            Race = "Husky",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4841),
                            Gender = "Female",
                            Name = "Zara",
                            Race = "Border-collie",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4843),
                            Gender = "Male",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4846),
                            Gender = "Male",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4847),
                            Gender = "Female",
                            Name = "Tunder",
                            Race = "Dog",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4849),
                            Gender = "Male",
                            Name = "Zira",
                            Race = "Husky",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Bella",
                            Race = "Labrador Retriever",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Rocky",
                            Race = "German Shepherd",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Luna",
                            Race = "Golden Retriever",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Max",
                            Race = "Poodle",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("OrganizerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 4,
                            Date = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 257, DateTimeKind.Local).AddTicks(4727),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "1",
                            Price = 0m,
                            Title = "Hondenwandeling in het bos"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 5,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 257, DateTimeKind.Local).AddTicks(4735),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "2",
                            Price = 10.50m,
                            Title = "Hondenshow Brussel"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 6,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 257, DateTimeKind.Local).AddTicks(4737),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "3",
                            Price = 0m,
                            Title = "Hondenwandeling aan zee"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 12,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 257, DateTimeKind.Local).AddTicks(4739),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "4",
                            Price = 10.50m,
                            Title = "Hondenshow West-Vlaanderen"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 13,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 257, DateTimeKind.Local).AddTicks(4741),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "5",
                            Price = 0m,
                            Title = "Hondenwandeling Heuvelland"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventsUser");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "1",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 5
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 4
                        },
                        new
                        {
                            UserId = "5",
                            EventId = 5
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1
                        },
                        new
                        {
                            Id = 3,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 6,
                            EventId = 2
                        },
                        new
                        {
                            Id = 7,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 8,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 9,
                            EventId = 2
                        },
                        new
                        {
                            Id = 10,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 12,
                            EventId = 3
                        },
                        new
                        {
                            Id = 13,
                            EventId = 2
                        },
                        new
                        {
                            Id = 14,
                            RouteId = 3
                        },
                        new
                        {
                            Id = 15,
                            EventId = 1
                        },
                        new
                        {
                            Id = 16,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 17,
                            RouteId = 3
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 7,
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4884),
                            Description = "Een mooie wandeling door het bos met je hond. Geniet van de natuur en de frisse lucht.",
                            Title = "Boswandeling",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 8,
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4886),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 9,
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4887),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 14,
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4889),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 15,
                            DateCreated = new DateTime(2024, 4, 26, 11, 53, 41, 255, DateTimeKind.Local).AddTicks(4891),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            AddressId = 3,
                            ConcurrencyStamp = "e7959b19-8493-46a7-bb8f-57221c43a2fd",
                            DateOfBirth = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            EmailConfirmed = false,
                            FirstName = "Jack",
                            Gender = "male",
                            LastName = "DeVos",
                            LockoutEnabled = false,
                            Password = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "93bbb08a-bfe1-47fa-9fc5-1dcac0e855da",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            AddressId = 10,
                            ConcurrencyStamp = "ceeddee9-65c7-420f-bd97-9166f497b034",
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            EmailConfirmed = false,
                            FirstName = "Jill",
                            Gender = "female",
                            LastName = "Vogels",
                            LockoutEnabled = false,
                            Password = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b17f3e57-10b0-412f-bd16-83532d8a5f75",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            AddressId = 11,
                            ConcurrencyStamp = "d9522450-a874-4b57-aec1-f929926d96a6",
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            EmailConfirmed = false,
                            FirstName = "Jim",
                            Gender = "male",
                            LastName = "Schoonaert",
                            LockoutEnabled = false,
                            Password = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc060825-c355-4c99-87d6-a81c330a0ff8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "f970bab7-ff73-40f6-8efe-bc415b7ecb6d",
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@pri.be",
                            EmailConfirmed = true,
                            FirstName = "John",
                            Gender = "male",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PRI.BE",
                            NormalizedUserName = "ADMIN@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAENsjaW23fXI/zRAIckmYJg7m0vAhlP2tMou+wyXjF9+Sm7l0TxwI3GcrlyoXVI2oIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a734246-af26-4f7f-9eda-f5ad55c79c7e",
                            TwoFactorEnabled = false,
                            UserName = "admin@pri.be"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AddressId = 2,
                            ConcurrencyStamp = "72f9c00a-abcc-44c3-bd71-d4975cb9f545",
                            DateOfBirth = new DateTime(1985, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            Gender = "female",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@PRI.BE",
                            NormalizedUserName = "USER@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEHn4n97yfqefH+wr9rVTcGjSjXSD0RaiqFxfbCt4uKj95rt1AU6oGhGI/tJoU6qUGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fcbf4378-31aa-44be-8d62-c40e89c818ab",
                            TwoFactorEnabled = false,
                            UserName = "user@pri.be"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Comments")
                        .HasForeignKey("RouteId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("AttendingUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("AttendingEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Images")
                        .HasForeignKey("RouteId");

                    b.Navigation("Event");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Navigation("AttendingUsers");

                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Navigation("AttendingEvents");

                    b.Navigation("Comments");

                    b.Navigation("Dogs");

                    b.Navigation("OrganizedEvents");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
