// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRI.Project.Rosseel_Almanzo.Infrastructure.Data;

#nullable disable

namespace PRI.Project.Rosseel_Almanzo.Infrastructure.Migrations
{
    [DbContext(typeof(SniffHikesDbContext))]
    [Migration("20240501151334_editUserEntityChanges")]
    partial class editUserEntityChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "10/05/1980 0:00:00",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "admin@pri.be",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "1",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "15/07/1985 0:00:00",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "user@pri.be",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "2",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Orginazer",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "20/09/1990 0:00:00",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "orginazer@pri.be",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "3",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "25/11/1995 0:00:00",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "jill@pri.be",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "4",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "30/01/2000 0:00:00",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "jim@pri.be",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "5",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 2,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gent",
                            Country = "Belgie",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 15"
                        },
                        new
                        {
                            Id = 4,
                            City = "Brugge",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 28"
                        },
                        new
                        {
                            Id = 5,
                            City = "Veurne",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Ooststraat 10"
                        },
                        new
                        {
                            Id = 6,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 7,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 8,
                            City = "Antwerpen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Meir 12"
                        },
                        new
                        {
                            Id = 9,
                            City = "Leuven",
                            Country = "België",
                            State = "Vlaams-Brabant",
                            Street = "Grote Markt 1"
                        },
                        new
                        {
                            Id = 10,
                            City = "Mechelen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Groenplaats 21"
                        },
                        new
                        {
                            Id = 11,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Oude Burg 12"
                        },
                        new
                        {
                            Id = 12,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 13,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 14,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 15,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(603),
                            EventId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(606),
                            EventId = 2,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(607),
                            EventId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(609),
                            EventId = 3,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(611),
                            RouteId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(612),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(614),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(616),
                            RouteId = 3,
                            UserId = "4"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(501),
                            Gender = "Male",
                            Name = "Inca",
                            Race = "Husky",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(539),
                            Gender = "Female",
                            Name = "Zara",
                            Race = "Border-collie",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(541),
                            Gender = "Male",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(544),
                            Gender = "Male",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(546),
                            Gender = "Female",
                            Name = "Tunder",
                            Race = "Dog",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(547),
                            Gender = "Male",
                            Name = "Zira",
                            Race = "Husky",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Bella",
                            Race = "Labrador Retriever",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Rocky",
                            Race = "German Shepherd",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Luna",
                            Race = "Golden Retriever",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Max",
                            Race = "Poodle",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("OrganizerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 4,
                            Date = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 474, DateTimeKind.Local).AddTicks(9733),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "1",
                            Price = 0m,
                            Title = "Hondenwandeling in het bos"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 5,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 474, DateTimeKind.Local).AddTicks(9743),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "2",
                            Price = 10.50m,
                            Title = "Hondenshow Brussel"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 6,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 474, DateTimeKind.Local).AddTicks(9746),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "3",
                            Price = 0m,
                            Title = "Hondenwandeling aan zee"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 12,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 474, DateTimeKind.Local).AddTicks(9748),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "4",
                            Price = 10.50m,
                            Title = "Hondenshow West-Vlaanderen"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 13,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 474, DateTimeKind.Local).AddTicks(9750),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "5",
                            Price = 0m,
                            Title = "Hondenwandeling Heuvelland"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventsUser");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "1",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 5
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 4
                        },
                        new
                        {
                            UserId = "5",
                            EventId = 5
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1
                        },
                        new
                        {
                            Id = 3,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 6,
                            EventId = 2
                        },
                        new
                        {
                            Id = 7,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 8,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 9,
                            EventId = 2
                        },
                        new
                        {
                            Id = 10,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 12,
                            EventId = 3
                        },
                        new
                        {
                            Id = 13,
                            EventId = 2
                        },
                        new
                        {
                            Id = 14,
                            RouteId = 3
                        },
                        new
                        {
                            Id = 15,
                            EventId = 1
                        },
                        new
                        {
                            Id = 16,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 17,
                            RouteId = 3
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 7,
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(631),
                            Description = "Een mooie wandeling door het bos met je hond. Geniet van de natuur en de frisse lucht.",
                            Title = "Boswandeling",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 8,
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(633),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 9,
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(635),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 14,
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(637),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 15,
                            DateCreated = new DateTime(2024, 5, 1, 17, 13, 33, 470, DateTimeKind.Local).AddTicks(638),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "6c20800f-d254-4c31-a98d-d016ebca9273",
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@pri.be",
                            EmailConfirmed = true,
                            FirstName = "John",
                            Gender = "male",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PRI.BE",
                            NormalizedUserName = "ADMIN@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEJnPdA0rOqFQRMSCSWpUKjd3at54Ie3enY+/Ly5jiiOowQItmZpOnGqtJCBQThvSLQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0f884dca-de03-40e0-83e4-044081fddf82",
                            TwoFactorEnabled = false,
                            UserName = "admin@pri.be"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AddressId = 2,
                            ConcurrencyStamp = "dffb7822-315a-4d92-a12f-b8c1b84158db",
                            DateOfBirth = new DateTime(1985, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            Gender = "female",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@PRI.BE",
                            NormalizedUserName = "USER@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEM44OyEGoEbSSIE4A8NqIdGH+5SWsXiUvFzTvCImPGpGrGYAxg+NQGahzfqwZgh19Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4cd706f2-6396-4037-8a38-7dc96a6652a0",
                            TwoFactorEnabled = false,
                            UserName = "user@pri.be"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            AddressId = 3,
                            ConcurrencyStamp = "68158105-3057-415c-87e8-926e7a47bd2a",
                            DateOfBirth = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orginazer@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jack",
                            Gender = "male",
                            LastName = "DeVos",
                            LockoutEnabled = false,
                            NormalizedEmail = "ORGINAZER@PRI.BE",
                            NormalizedUserName = "ORGINAZER@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEELY3KY/8s1tGPwVA1QPLb84PsYtMamvbjvrTDoO10w3rfLj/Q0NqkrnhkNq/0fv4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37c057f8-927e-49e3-ac90-8ae0e57d60ac",
                            TwoFactorEnabled = false,
                            UserName = "orginazer@pri.be"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            AddressId = 10,
                            ConcurrencyStamp = "5dfc5533-263a-4e45-a134-5c40cb2a921f",
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jill@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jill",
                            Gender = "female",
                            LastName = "Vogels",
                            LockoutEnabled = false,
                            NormalizedEmail = "JILL@PRI.BE",
                            NormalizedUserName = "JILL@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEHOkGPNxqRp13cPSKuiJR59gBbStB9B1Crj12vR0Dy635DAZxSr87u7CwfxWDlBwqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f797d54f-54b2-49f4-a144-7db588e4c3c5",
                            TwoFactorEnabled = false,
                            UserName = "jill@pri.be"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            AddressId = 11,
                            ConcurrencyStamp = "8735b09a-998a-4806-ad1b-916542fc8fb4",
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jim@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jim",
                            Gender = "male",
                            LastName = "Schoonaert",
                            LockoutEnabled = false,
                            NormalizedEmail = "JIM@PRI.BE",
                            NormalizedUserName = "JIM@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEHfMfOIn4adJlsYhpgLzIiydidKImB7DDD7ZptGnKFU/nmXgG8/fVz5/1sIwgbXcRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97155df2-a1f1-440f-b2dd-b5ffd8299e8b",
                            TwoFactorEnabled = false,
                            UserName = "jim@pri.be"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Comments")
                        .HasForeignKey("RouteId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("AttendingUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("AttendingEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Images")
                        .HasForeignKey("RouteId");

                    b.Navigation("Event");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Navigation("AttendingUsers");

                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Navigation("AttendingEvents");

                    b.Navigation("Comments");

                    b.Navigation("Dogs");

                    b.Navigation("OrganizedEvents");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
