// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRI.Project.Rosseel_Almanzo.Infrastructure.Data;

#nullable disable

namespace PRI.Project.Rosseel_Almanzo.Infrastructure.Migrations
{
    [DbContext(typeof(SniffHikesDbContext))]
    [Migration("20240615163210_addImages")]
    partial class addImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "10/05/1980 0:00:00",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "admin@pri.be",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "1",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "15/07/1985 0:00:00",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "user@pri.be",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "2",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Orginazer",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "20/09/1990 0:00:00",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "orginazer@pri.be",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "3",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "25/11/1995 0:00:00",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "jill@pri.be",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "4",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "User",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth",
                            ClaimValue = "30/01/2000 0:00:00",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                            ClaimValue = "jim@pri.be",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
                            ClaimValue = "5",
                            UserId = "5"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "profile-image",
                            ClaimValue = "FB_IMG_1676153444794.jpg",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "profile-image",
                            ClaimValue = "AInca&me_153848.jpeg",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "profile-image",
                            ClaimValue = "received_3074607475886000.jpeg",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 2,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gent",
                            Country = "Belgie",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 15"
                        },
                        new
                        {
                            Id = 4,
                            City = "Brugge",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 28"
                        },
                        new
                        {
                            Id = 5,
                            City = "Veurne",
                            Country = "Belgie",
                            State = "West-Vlaanderen",
                            Street = "Ooststraat 10"
                        },
                        new
                        {
                            Id = 6,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 7,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 8,
                            City = "Antwerpen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Meir 12"
                        },
                        new
                        {
                            Id = 9,
                            City = "Leuven",
                            Country = "België",
                            State = "Vlaams-Brabant",
                            Street = "Grote Markt 1"
                        },
                        new
                        {
                            Id = 10,
                            City = "Mechelen",
                            Country = "België",
                            State = "Antwerpen",
                            Street = "Groenplaats 21"
                        },
                        new
                        {
                            Id = 11,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Oude Burg 12"
                        },
                        new
                        {
                            Id = 12,
                            City = "Gent",
                            Country = "België",
                            State = "Oost-Vlaanderen",
                            Street = "Veldstraat 9"
                        },
                        new
                        {
                            Id = 13,
                            City = "Brugge",
                            Country = "België",
                            State = "West-Vlaanderen",
                            Street = "Steenstraat 21"
                        },
                        new
                        {
                            Id = 14,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        },
                        new
                        {
                            Id = 15,
                            City = "Anderlecht",
                            Country = "Belgie",
                            State = "Brussel",
                            Street = "Rue Wayez 3"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3817),
                            EventId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3819),
                            EventId = 2,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3821),
                            EventId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Gezellige avond!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3823),
                            EventId = 3,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3824),
                            RouteId = 1,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Leuke wandeling!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3826),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3828),
                            RouteId = 2,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Mooie route!",
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3830),
                            RouteId = 3,
                            UserId = "4"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3764),
                            Gender = "Male",
                            Image = "inca2.jpg",
                            Name = "Inca",
                            Race = "Husky",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3803),
                            Gender = "Female",
                            Image = "FB_IMG_1676153391880.jpg",
                            Name = "Zara",
                            Race = "Border-collie",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3806),
                            Gender = "Male",
                            Image = "IMG_20201118_121810.jpg",
                            Name = "Zira",
                            Race = "Husky",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3808),
                            Gender = "Male",
                            Image = "received_455341335122662.jpeg",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3810),
                            Gender = "Male",
                            Image = "IMG_20210613_142801.jpg",
                            Name = "Sleepy",
                            Race = "Duitse-herder",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2020, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Image = "IMG_20210619_162819.jpg",
                            Name = "Luna",
                            Race = "Golden Retriever",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Image = "received_421419258529965.jpeg",
                            Name = "Max",
                            Race = "Poodle",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("OrganizerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 4,
                            Date = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 634, DateTimeKind.Local).AddTicks(3031),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "1",
                            Price = 0m,
                            Title = "Hondenwandeling in het bos"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 5,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 634, DateTimeKind.Local).AddTicks(3037),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "2",
                            Price = 10.50m,
                            Title = "Hondenshow Brussel"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 6,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 634, DateTimeKind.Local).AddTicks(3039),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "3",
                            Price = 0m,
                            Title = "Hondenwandeling aan zee"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 12,
                            Date = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 634, DateTimeKind.Local).AddTicks(3041),
                            Description = "Kom en bewonder verschillende hondenrassen tijdens de hondenshow in Brussel. Er zijn prijzen te winnen en veel plezier te beleven!",
                            OrganizerId = "4",
                            Price = 10.50m,
                            Title = "Hondenshow West-Vlaanderen"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 13,
                            Date = new DateTime(2024, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 634, DateTimeKind.Local).AddTicks(3043),
                            Description = "Geniet van een ontspannen wandeling met je hond in het prachtige bosgebied. Neem je viervoeter mee voor een leuke tijd in de natuur.",
                            OrganizerId = "5",
                            Price = 0m,
                            Title = "Hondenwandeling Heuvelland"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventsUser");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 1
                        },
                        new
                        {
                            UserId = "2",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 2
                        },
                        new
                        {
                            UserId = "1",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "3",
                            EventId = 3
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 5
                        },
                        new
                        {
                            UserId = "4",
                            EventId = 4
                        },
                        new
                        {
                            UserId = "5",
                            EventId = 5
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            File = "AHiken.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            File = "IMG_20210516_165116.jpg"
                        },
                        new
                        {
                            Id = 3,
                            EventId = 1,
                            File = "IMG_20210516_171528.jpg"
                        },
                        new
                        {
                            Id = 4,
                            EventId = 2,
                            File = "Schermafbeelding 2024-06-15 173550.png"
                        },
                        new
                        {
                            Id = 5,
                            EventId = 2,
                            File = "Schermafbeelding 2023-11-03 203719.png"
                        },
                        new
                        {
                            Id = 6,
                            EventId = 2,
                            File = "Schermafbeelding 2024-06-15 173812.png"
                        },
                        new
                        {
                            Id = 7,
                            EventId = 3,
                            File = "FB_IMG_1676153401593.jpg"
                        },
                        new
                        {
                            Id = 8,
                            EventId = 3,
                            File = "IMG_20210613_150444.jpg"
                        },
                        new
                        {
                            Id = 9,
                            EventId = 4,
                            File = "Schermafbeelding 2024-06-15 175152.png"
                        },
                        new
                        {
                            Id = 10,
                            EventId = 5,
                            File = "IMG_20210620_161504.jpg"
                        },
                        new
                        {
                            Id = 11,
                            File = "IMG_20210620_152407.jpg",
                            RouteId = 1
                        },
                        new
                        {
                            Id = 12,
                            File = "IMG_20210620_154507.jpg",
                            RouteId = 1
                        },
                        new
                        {
                            Id = 13,
                            File = "IMG_20210620_154515.jpg",
                            RouteId = 1
                        },
                        new
                        {
                            Id = 14,
                            File = "Schermafbeelding 2024-06-15 180613.png",
                            RouteId = 2
                        },
                        new
                        {
                            Id = 15,
                            File = "Schermafbeelding 2024-06-15 180627.png",
                            RouteId = 2
                        },
                        new
                        {
                            Id = 16,
                            File = "Schermafbeelding 2024-06-15 180646.png",
                            RouteId = 2
                        },
                        new
                        {
                            Id = 17,
                            File = "Schermafbeelding 2024-06-15 180856.png",
                            RouteId = 3
                        },
                        new
                        {
                            Id = 18,
                            File = "Schermafbeelding 2024-06-15 180954.png",
                            RouteId = 3
                        },
                        new
                        {
                            Id = 19,
                            File = "Schermafbeelding 2024-06-15 181114.png",
                            RouteId = 4
                        },
                        new
                        {
                            Id = 20,
                            File = "Schermafbeelding 2024-06-15 181021.png",
                            RouteId = 5
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 7,
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3874),
                            Description = "Een mooie wandeling door het bos met je hond. Geniet van de natuur en de frisse lucht.",
                            Title = "HellegatBos wandeling",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 8,
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3876),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling DePanne",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 9,
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3878),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling Brussel",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 14,
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3879),
                            Description = "Een ontspannen wandeling met je hond langs het strand. Laat je viervoeter lekker uitwaaien!",
                            Title = "Strandwandeling Oostende",
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 15,
                            DateCreated = new DateTime(2024, 6, 15, 18, 32, 9, 629, DateTimeKind.Local).AddTicks(3881),
                            Description = "Een leuke wandeling met je hond door het park. Laat je hond lekker rennen en spelen.",
                            Title = "Parkwandeling Brugge",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "18032c48-62a6-40bc-bf80-a81a74c951f7",
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@pri.be",
                            EmailConfirmed = true,
                            FirstName = "John",
                            Gender = "male",
                            Image = "FB_IMG_1676153444794.jpg",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PRI.BE",
                            NormalizedUserName = "ADMIN@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAECS7AUcRmJzq/DuHmwq9eMBmTPe2RkjVrLwlodJxvk46qZc7w0Jd8oBWLoNXU8YKGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "99ef2440-3680-4aa8-a0b4-98a75e9d9bf4",
                            TwoFactorEnabled = false,
                            UserName = "admin@pri.be"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AddressId = 2,
                            ConcurrencyStamp = "064861f8-1d34-4536-b815-09747e8d8f0a",
                            DateOfBirth = new DateTime(1985, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            Gender = "female",
                            Image = "AInca&me_153848.jpeg",
                            LastName = "DeWachter",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@PRI.BE",
                            NormalizedUserName = "USER@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEExbmaaji21xEOihayQGa7b/ixDIFioBYSY3mGDZ4xByW3ThCQuRjDGHtBLgg3STmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb9dbf6a-cc0a-462d-88c2-0ad62ffa541a",
                            TwoFactorEnabled = false,
                            UserName = "user@pri.be"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            AddressId = 3,
                            ConcurrencyStamp = "255aa8a8-0b9d-4834-b177-2f0d1621f8ce",
                            DateOfBirth = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orginazer@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jack",
                            Gender = "male",
                            Image = "received_3074607475886000.jpeg",
                            LastName = "DeVos",
                            LockoutEnabled = false,
                            NormalizedEmail = "ORGINAZER@PRI.BE",
                            NormalizedUserName = "ORGINAZER@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEDiXYQLNVlgcr0tymnUdmUHasPtF35MIMfsv3ft6MlzxfpnU4Vfk+Z5hpilwHU0GfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f623afd-5ae1-49b2-b9e4-dd192c503204",
                            TwoFactorEnabled = false,
                            UserName = "orginazer@pri.be"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            AddressId = 10,
                            ConcurrencyStamp = "3aa2ab82-34ad-4d94-8532-c84f0854e1a6",
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jill@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jill",
                            Gender = "female",
                            LastName = "Vogels",
                            LockoutEnabled = false,
                            NormalizedEmail = "JILL@PRI.BE",
                            NormalizedUserName = "JILL@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEO5wKG54pZh4UW6ke1obdNS2msi9dB2dARcgwqttVA1UMP1Z7wYpZ91gpKZU3qVw+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0163b857-ad41-4e6e-8e7f-6ee701481182",
                            TwoFactorEnabled = false,
                            UserName = "jill@pri.be"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            AddressId = 11,
                            ConcurrencyStamp = "22efeb95-a6bf-4197-b918-7b37d20a5c7f",
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jim@pri.be",
                            EmailConfirmed = true,
                            FirstName = "Jim",
                            Gender = "male",
                            LastName = "Schoonaert",
                            LockoutEnabled = false,
                            NormalizedEmail = "JIM@PRI.BE",
                            NormalizedUserName = "JIM@PRI.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAECy3t5TPXpRTofdBIyfAQbvWWqT0NHAIK2lTMhzrMJ1KjhIGJjcH0BqbIAPbEKMM5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d54e6f83-0b93-42e5-bc7d-c1b524998d7a",
                            TwoFactorEnabled = false,
                            UserName = "jim@pri.be"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Comment", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Comments")
                        .HasForeignKey("RouteId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Dog", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Dogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Address");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.EventUser", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("AttendingUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("AttendingEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Image", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId");

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", "Route")
                        .WithMany("Images")
                        .HasForeignKey("RouteId");

                    b.Navigation("Event");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.HasOne("PRI.Project.Rosseel_Almanzo.Core.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Event", b =>
                {
                    b.Navigation("AttendingUsers");

                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.Route", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PRI.Project.Rosseel_Almanzo.Core.Entities.User", b =>
                {
                    b.Navigation("AttendingEvents");

                    b.Navigation("Comments");

                    b.Navigation("Dogs");

                    b.Navigation("OrganizedEvents");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
